export const VITE_PUBLIC_API_URL = import.meta.env.VITE_PUBLIC_API_URL;
export const VITE_PUBLIC_API_URL_BANNERS = import.meta.env.VITE_PUBLIC_API_URL_BANNERS;

export const VITE_PUBLIC_API_URL_TEMPLATE_FRONTEND = import.meta.env.VITE_PUBLIC_API_URL_TEMPLATE_FRONTEND;
export const VITE_PUBLIC_STOREFRONT_URL = import.meta.env.VITE_PUBLIC_STOREFRONT_URL;

export const VITE_PUBLIC_IMAGEKIT_PUBLIC_KEY = import.meta.env.VITE_PUBLIC_IMAGEKIT_PUBLIC_KEY;
export const VITE_IMAGEKIT_URL_ENDPOINT = import.meta.env.VITE_IMAGEKIT_URL_ENDPOINT;
