/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as TemplateVendorIdIndexRouteImport } from './routes/template/$vendorId/index'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor/index'
import { Route as AuthenticatedVendorTemplateIndexRouteImport } from './routes/_authenticated/vendor-template/index'
import { Route as AuthenticatedVendorTemplateOtherIndexRouteImport } from './routes/_authenticated/vendor-template-other/index'
import { Route as AuthenticatedVendorTemplateContactIndexRouteImport } from './routes/_authenticated/vendor-template-contact/index'
import { Route as AuthenticatedVendorTemplateAboutIndexRouteImport } from './routes/_authenticated/vendor-template-about/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUploadProductsIndexRouteImport } from './routes/_authenticated/upload-products/index'
import { Route as AuthenticatedSubcategoryIndexRouteImport } from './routes/_authenticated/subcategory/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOrderIndexRouteImport } from './routes/_authenticated/order/index'
import { Route as AuthenticatedInventoryManagementIndexRouteImport } from './routes/_authenticated/inventory-management/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCategoryIndexRouteImport } from './routes/_authenticated/category/index'
import { Route as AuthenticatedBannersIndexRouteImport } from './routes/_authenticated/banners/index'
import { Route as TemplateVendorIdContactRouteImport } from './routes/template/$vendorId/contact'
import { Route as TemplateVendorIdAboutRouteImport } from './routes/template/$vendorId/about'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProductsCreateProductsIndexRouteImport } from './routes/_authenticated/products/create-products/index'
import { Route as AuthenticatedProductsAdminProductsIndexRouteImport } from './routes/_authenticated/products/admin-products/index'
import { Route as AuthenticatedCategoryCreateCategoryIndexRouteImport } from './routes/_authenticated/category/create-category/index'
import { Route as TemplateVendorIdProductProductIdRouteImport } from './routes/template/$vendorId/product/$productId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const TemplateVendorIdIndexRoute = TemplateVendorIdIndexRouteImport.update({
  id: '/template/$vendorId/',
  path: '/template/$vendorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/vendor/',
    path: '/vendor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateIndexRoute =
  AuthenticatedVendorTemplateIndexRouteImport.update({
    id: '/vendor-template/',
    path: '/vendor-template/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateOtherIndexRoute =
  AuthenticatedVendorTemplateOtherIndexRouteImport.update({
    id: '/vendor-template-other/',
    path: '/vendor-template-other/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateContactIndexRoute =
  AuthenticatedVendorTemplateContactIndexRouteImport.update({
    id: '/vendor-template-contact/',
    path: '/vendor-template-contact/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorTemplateAboutIndexRoute =
  AuthenticatedVendorTemplateAboutIndexRouteImport.update({
    id: '/vendor-template-about/',
    path: '/vendor-template-about/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadProductsIndexRoute =
  AuthenticatedUploadProductsIndexRouteImport.update({
    id: '/upload-products/',
    path: '/upload-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubcategoryIndexRoute =
  AuthenticatedSubcategoryIndexRouteImport.update({
    id: '/subcategory/',
    path: '/subcategory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderIndexRoute = AuthenticatedOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryManagementIndexRoute =
  AuthenticatedInventoryManagementIndexRouteImport.update({
    id: '/inventory-management/',
    path: '/inventory-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoryIndexRoute =
  AuthenticatedCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBannersIndexRoute =
  AuthenticatedBannersIndexRouteImport.update({
    id: '/banners/',
    path: '/banners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TemplateVendorIdContactRoute = TemplateVendorIdContactRouteImport.update({
  id: '/template/$vendorId/contact',
  path: '/template/$vendorId/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateVendorIdAboutRoute = TemplateVendorIdAboutRouteImport.update({
  id: '/template/$vendorId/about',
  path: '/template/$vendorId/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsCreateProductsIndexRoute =
  AuthenticatedProductsCreateProductsIndexRouteImport.update({
    id: '/products/create-products/',
    path: '/products/create-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsAdminProductsIndexRoute =
  AuthenticatedProductsAdminProductsIndexRouteImport.update({
    id: '/products/admin-products/',
    path: '/products/admin-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoryCreateCategoryIndexRoute =
  AuthenticatedCategoryCreateCategoryIndexRouteImport.update({
    id: '/category/create-category/',
    path: '/category/create-category/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TemplateVendorIdProductProductIdRoute =
  TemplateVendorIdProductProductIdRouteImport.update({
    id: '/template/$vendorId/product/$productId',
    path: '/template/$vendorId/product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/banners': typeof AuthenticatedBannersIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementIndexRoute
  '/order': typeof AuthenticatedOrderIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/subcategory': typeof AuthenticatedSubcategoryIndexRoute
  '/upload-products': typeof AuthenticatedUploadProductsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendor-template-about': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/vendor-template-contact': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/vendor-template-other': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/vendor-template': typeof AuthenticatedVendorTemplateIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/template/$vendorId': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/category/create-category': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/products/admin-products': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/products/create-products': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/banners': typeof AuthenticatedBannersIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementIndexRoute
  '/order': typeof AuthenticatedOrderIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/subcategory': typeof AuthenticatedSubcategoryIndexRoute
  '/upload-products': typeof AuthenticatedUploadProductsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendor-template-about': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/vendor-template-contact': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/vendor-template-other': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/vendor-template': typeof AuthenticatedVendorTemplateIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/template/$vendorId': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/category/create-category': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/products/admin-products': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/products/create-products': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/template/$vendorId/about': typeof TemplateVendorIdAboutRoute
  '/template/$vendorId/contact': typeof TemplateVendorIdContactRoute
  '/_authenticated/banners/': typeof AuthenticatedBannersIndexRoute
  '/_authenticated/category/': typeof AuthenticatedCategoryIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/inventory-management/': typeof AuthenticatedInventoryManagementIndexRoute
  '/_authenticated/order/': typeof AuthenticatedOrderIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/subcategory/': typeof AuthenticatedSubcategoryIndexRoute
  '/_authenticated/upload-products/': typeof AuthenticatedUploadProductsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vendor-template-about/': typeof AuthenticatedVendorTemplateAboutIndexRoute
  '/_authenticated/vendor-template-contact/': typeof AuthenticatedVendorTemplateContactIndexRoute
  '/_authenticated/vendor-template-other/': typeof AuthenticatedVendorTemplateOtherIndexRoute
  '/_authenticated/vendor-template/': typeof AuthenticatedVendorTemplateIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/template/$vendorId/': typeof TemplateVendorIdIndexRoute
  '/template/$vendorId/product/$productId': typeof TemplateVendorIdProductProductIdRoute
  '/_authenticated/category/create-category/': typeof AuthenticatedCategoryCreateCategoryIndexRoute
  '/_authenticated/products/admin-products/': typeof AuthenticatedProductsAdminProductsIndexRoute
  '/_authenticated/products/create-products/': typeof AuthenticatedProductsCreateProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/contact'
    | '/banners'
    | '/category'
    | '/chats'
    | '/help-center'
    | '/inventory-management'
    | '/order'
    | '/products'
    | '/profile'
    | '/subcategory'
    | '/upload-products'
    | '/users'
    | '/vendor-template-about'
    | '/vendor-template-contact'
    | '/vendor-template-other'
    | '/vendor-template'
    | '/vendor'
    | '/template/$vendorId'
    | '/template/$vendorId/product/$productId'
    | '/category/create-category'
    | '/products/admin-products'
    | '/products/create-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/contact'
    | '/banners'
    | '/category'
    | '/chats'
    | '/help-center'
    | '/inventory-management'
    | '/order'
    | '/products'
    | '/profile'
    | '/subcategory'
    | '/upload-products'
    | '/users'
    | '/vendor-template-about'
    | '/vendor-template-contact'
    | '/vendor-template-other'
    | '/vendor-template'
    | '/vendor'
    | '/template/$vendorId'
    | '/template/$vendorId/product/$productId'
    | '/category/create-category'
    | '/products/admin-products'
    | '/products/create-products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/template/$vendorId/about'
    | '/template/$vendorId/contact'
    | '/_authenticated/banners/'
    | '/_authenticated/category/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/inventory-management/'
    | '/_authenticated/order/'
    | '/_authenticated/products/'
    | '/_authenticated/profile/'
    | '/_authenticated/subcategory/'
    | '/_authenticated/upload-products/'
    | '/_authenticated/users/'
    | '/_authenticated/vendor-template-about/'
    | '/_authenticated/vendor-template-contact/'
    | '/_authenticated/vendor-template-other/'
    | '/_authenticated/vendor-template/'
    | '/_authenticated/vendor/'
    | '/template/$vendorId/'
    | '/template/$vendorId/product/$productId'
    | '/_authenticated/category/create-category/'
    | '/_authenticated/products/admin-products/'
    | '/_authenticated/products/create-products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  TemplateVendorIdAboutRoute: typeof TemplateVendorIdAboutRoute
  TemplateVendorIdContactRoute: typeof TemplateVendorIdContactRoute
  TemplateVendorIdIndexRoute: typeof TemplateVendorIdIndexRoute
  TemplateVendorIdProductProductIdRoute: typeof TemplateVendorIdProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/template/$vendorId/': {
      id: '/template/$vendorId/'
      path: '/template/$vendorId'
      fullPath: '/template/$vendorId'
      preLoaderRoute: typeof TemplateVendorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template/': {
      id: '/_authenticated/vendor-template/'
      path: '/vendor-template'
      fullPath: '/vendor-template'
      preLoaderRoute: typeof AuthenticatedVendorTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-other/': {
      id: '/_authenticated/vendor-template-other/'
      path: '/vendor-template-other'
      fullPath: '/vendor-template-other'
      preLoaderRoute: typeof AuthenticatedVendorTemplateOtherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-contact/': {
      id: '/_authenticated/vendor-template-contact/'
      path: '/vendor-template-contact'
      fullPath: '/vendor-template-contact'
      preLoaderRoute: typeof AuthenticatedVendorTemplateContactIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-template-about/': {
      id: '/_authenticated/vendor-template-about/'
      path: '/vendor-template-about'
      fullPath: '/vendor-template-about'
      preLoaderRoute: typeof AuthenticatedVendorTemplateAboutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload-products/': {
      id: '/_authenticated/upload-products/'
      path: '/upload-products'
      fullPath: '/upload-products'
      preLoaderRoute: typeof AuthenticatedUploadProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subcategory/': {
      id: '/_authenticated/subcategory/'
      path: '/subcategory'
      fullPath: '/subcategory'
      preLoaderRoute: typeof AuthenticatedSubcategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/': {
      id: '/_authenticated/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthenticatedOrderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory-management/': {
      id: '/_authenticated/inventory-management/'
      path: '/inventory-management'
      fullPath: '/inventory-management'
      preLoaderRoute: typeof AuthenticatedInventoryManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/': {
      id: '/_authenticated/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AuthenticatedCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banners/': {
      id: '/_authenticated/banners/'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/template/$vendorId/contact': {
      id: '/template/$vendorId/contact'
      path: '/template/$vendorId/contact'
      fullPath: '/template/$vendorId/contact'
      preLoaderRoute: typeof TemplateVendorIdContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$vendorId/about': {
      id: '/template/$vendorId/about'
      path: '/template/$vendorId/about'
      fullPath: '/template/$vendorId/about'
      preLoaderRoute: typeof TemplateVendorIdAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/create-products/': {
      id: '/_authenticated/products/create-products/'
      path: '/products/create-products'
      fullPath: '/products/create-products'
      preLoaderRoute: typeof AuthenticatedProductsCreateProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/admin-products/': {
      id: '/_authenticated/products/admin-products/'
      path: '/products/admin-products'
      fullPath: '/products/admin-products'
      preLoaderRoute: typeof AuthenticatedProductsAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/create-category/': {
      id: '/_authenticated/category/create-category/'
      path: '/category/create-category'
      fullPath: '/category/create-category'
      preLoaderRoute: typeof AuthenticatedCategoryCreateCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/template/$vendorId/product/$productId': {
      id: '/template/$vendorId/product/$productId'
      path: '/template/$vendorId/product/$productId'
      fullPath: '/template/$vendorId/product/$productId'
      preLoaderRoute: typeof TemplateVendorIdProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedBannersIndexRoute: typeof AuthenticatedBannersIndexRoute
  AuthenticatedCategoryIndexRoute: typeof AuthenticatedCategoryIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInventoryManagementIndexRoute: typeof AuthenticatedInventoryManagementIndexRoute
  AuthenticatedOrderIndexRoute: typeof AuthenticatedOrderIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedSubcategoryIndexRoute: typeof AuthenticatedSubcategoryIndexRoute
  AuthenticatedUploadProductsIndexRoute: typeof AuthenticatedUploadProductsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVendorTemplateAboutIndexRoute: typeof AuthenticatedVendorTemplateAboutIndexRoute
  AuthenticatedVendorTemplateContactIndexRoute: typeof AuthenticatedVendorTemplateContactIndexRoute
  AuthenticatedVendorTemplateOtherIndexRoute: typeof AuthenticatedVendorTemplateOtherIndexRoute
  AuthenticatedVendorTemplateIndexRoute: typeof AuthenticatedVendorTemplateIndexRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedCategoryCreateCategoryIndexRoute: typeof AuthenticatedCategoryCreateCategoryIndexRoute
  AuthenticatedProductsAdminProductsIndexRoute: typeof AuthenticatedProductsAdminProductsIndexRoute
  AuthenticatedProductsCreateProductsIndexRoute: typeof AuthenticatedProductsCreateProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedBannersIndexRoute: AuthenticatedBannersIndexRoute,
  AuthenticatedCategoryIndexRoute: AuthenticatedCategoryIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInventoryManagementIndexRoute:
    AuthenticatedInventoryManagementIndexRoute,
  AuthenticatedOrderIndexRoute: AuthenticatedOrderIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedSubcategoryIndexRoute: AuthenticatedSubcategoryIndexRoute,
  AuthenticatedUploadProductsIndexRoute: AuthenticatedUploadProductsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVendorTemplateAboutIndexRoute:
    AuthenticatedVendorTemplateAboutIndexRoute,
  AuthenticatedVendorTemplateContactIndexRoute:
    AuthenticatedVendorTemplateContactIndexRoute,
  AuthenticatedVendorTemplateOtherIndexRoute:
    AuthenticatedVendorTemplateOtherIndexRoute,
  AuthenticatedVendorTemplateIndexRoute: AuthenticatedVendorTemplateIndexRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
  AuthenticatedCategoryCreateCategoryIndexRoute:
    AuthenticatedCategoryCreateCategoryIndexRoute,
  AuthenticatedProductsAdminProductsIndexRoute:
    AuthenticatedProductsAdminProductsIndexRoute,
  AuthenticatedProductsCreateProductsIndexRoute:
    AuthenticatedProductsCreateProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  TemplateVendorIdAboutRoute: TemplateVendorIdAboutRoute,
  TemplateVendorIdContactRoute: TemplateVendorIdContactRoute,
  TemplateVendorIdIndexRoute: TemplateVendorIdIndexRoute,
  TemplateVendorIdProductProductIdRoute: TemplateVendorIdProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
